# Generated by Django 6.0.6 on 2026-08-29 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(help_text='رقم مرجعي فريد للطلب مثل: ITQ-2026-5821', max_length=30, unique=True, verbose_name='الرقم المرجعي')),
                ('full_name_ar', models.CharField(max_length=255, verbose_name='الاسم بالعربي')),
                ('full_name_en', models.CharField(blank=True, default='', max_length=255, verbose_name='الاسم بالإنجليزي')),
                ('phone', models.CharField(max_length=30, verbose_name='رقم الجوال')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('birth_place', models.CharField(blank=True, default='', max_length=150, verbose_name='مكان الميلاد')),
                ('course_id', models.CharField(max_length=50, verbose_name='معرف الدورة')),
                ('course_title', models.CharField(max_length=255, verbose_name='اسم الدورة')),
                ('receipt_file', models.FileField(help_text='صورة أو مستند سند الحوالة / الإيداع (JPG, PNG, PDF — حد أقصى 5MB)', upload_to='receipts/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: JPG, JPEG, PNG, PDF')], verbose_name='سند الدفع')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='حالة الطلب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'طلب تسجيل',
                'verbose_name_plural': 'طلبات التسجيل',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('phone', 'course_id'), name='unique_phone_course', violation_error_message='رقم الجوال مسجل مسبقاً في هذه الدورة')],
            },
        ),
    ]
