# Generated by Django 6.0.6 on 2026-09-04 22:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='receipt_file',
            field=models.FileField(help_text='صورة أو مستند سند الحوالة / الإيداع (JPG, PNG, WEBP, PDF — حد أقصى 5MB)', upload_to='receipts/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf', 'webp'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: JPG, JPEG, PNG, PDF, WEBP')], verbose_name='سند الدفع'),
        ),
    ]
