# Generated by Django 6.0.6 on 2026-09-20 01:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_alter_registration_receipt_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='attendance_mode',
            field=models.CharField(choices=[('in_person', 'حضوري'), ('online', 'عن بعد')], default='in_person', max_length=30, verbose_name='نمط الحضور'),
        ),
        migrations.AddField(
            model_name='registration',
            name='residence_location',
            field=models.CharField(choices=[('inside_yemen', 'داخل الوطن (اليمن)'), ('outside_yemen', 'خارج الوطن (بلد آخر)')], default='inside_yemen', max_length=30, verbose_name='موقع الإقامة'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='birth_place',
            field=models.CharField(max_length=150, verbose_name='مكان الميلاد'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='full_name_en',
            field=models.CharField(max_length=255, verbose_name='الاسم بالإنجليزي'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='receipt_file',
            field=models.FileField(blank=True, help_text='صورة أو مستند سند الحوالة / الإيداع (JPG, PNG, WEBP, PDF — حد أقصى 5MB)', null=True, upload_to='receipts/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf', 'webp'], message='صيغة الملف غير مدعومة. الصيغ المسموحة: JPG, JPEG, PNG, PDF, WEBP')], verbose_name='سند الدفع'),
        ),
    ]
