# Generated by Django 6.0.6 on 2026-09-21 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_registration_attendance_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(help_text='رمز أو كود فريد للدورة مثل: C001_CPP_BASICS أو C010_CYBER', max_length=50, unique=True, verbose_name='معرف الدورة الفريد')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان / اسم الدورة')),
                ('track', models.CharField(help_text='مثال: هندسة البرمجيات والمنطق البرمجي', max_length=150, verbose_name='اسم المسار المعروض')),
                ('track_key', models.CharField(choices=[('programming', 'البرمجة وهندسة البرمجيات'), ('ai', 'الذكاء الاصطناعي والبيانات'), ('languages', 'اللغات والترجمة'), ('skills', 'المهارات والأنظمة والحاسوب'), ('other', 'مسار تدريبي عام / تخصصي آخر')], default='programming', max_length=50, verbose_name='تصنيف المسار (للفلترة)')),
                ('description', models.TextField(verbose_name='وصف الدورة')),
                ('duration', models.CharField(default='شهر تدريبي (40 ساعة تدريبية)', max_length=100, verbose_name='المدة التدريبية والساعات')),
                ('level', models.CharField(default='من الصفر والمبتدئين', max_length=100, verbose_name='المستوى المستهدف')),
                ('badge', models.CharField(blank=True, default='دورة تخصصية', help_text='مثال: دورة أساسيات (شهر)، دبلوم معتمد، إلخ', max_length=100, verbose_name='الشارة العلوية (Badge)')),
                ('icon', models.CharField(default='book-open', help_text='اسم الأيقونة مثل: terminal, layers, file-code-2, cpu, database, sparkle, globe, monitor', max_length=50, verbose_name='أيقونة Lucide')),
                ('color', models.CharField(default='#2563EB', help_text='مثال: #2563EB, #10B981, #7C3AED, #D97706', max_length=30, verbose_name='كود اللون الأساسي (#hex)')),
                ('bg_color', models.CharField(default='#EFF6FF', help_text='مثال: #EFF6FF, #ECFDF5, #F5F3FF, #FFFBEB', max_length=30, verbose_name='كود لون الخلفية (#hex)')),
                ('status', models.CharField(choices=[('active', 'نشطة ومتاحة للتسجيل'), ('suspended', 'موقفة حالياً (معطلة مؤقتاً)')], default='active', max_length=20, verbose_name='حالة الدورة والتسجيل')),
                ('allow_in_person', models.BooleanField(default=True, verbose_name='إتاحة التدريب الحضوري بالمقر')),
                ('allow_online', models.BooleanField(default=True, verbose_name='إتاحة التدريب عن بعد (Online)')),
                ('min_students', models.PositiveIntegerField(default=15, verbose_name='الحد الأدنى للبدء (طالب)')),
                ('max_students', models.PositiveIntegerField(default=30, verbose_name='الحد الأقصى للسعة (مقعد)')),
                ('price_in_person_current', models.PositiveIntegerField(default=20000, verbose_name='رسوم التدريب الحضوري الحالية (ريال)')),
                ('price_in_person_original', models.PositiveIntegerField(blank=True, default=25000, null=True, verbose_name='رسوم الحضوري قبل الخصم (اختياري)')),
                ('price_online_current', models.PositiveIntegerField(default=15000, verbose_name='رسوم التدريب عن بعد Online الحالية (ريال)')),
                ('price_online_original', models.PositiveIntegerField(blank=True, default=20000, null=True, verbose_name='رسوم الأونلاين قبل الخصم (اختياري)')),
                ('price_certificate', models.CharField(default='شاملة الشهادة المعتمدة', max_length=150, verbose_name='ملاحظة الشهادة')),
                ('prerequisite', models.CharField(blank=True, max_length=255, null=True, verbose_name='المتطلب السابق (إن وجد)')),
                ('laptop_required', models.BooleanField(default=False, verbose_name='يشترط إحضار لابتوب خاص')),
                ('topics', models.TextField(blank=True, help_text='اكتب كل محور في سطر مستقل', verbose_name='محاور ومفردات الدورة')),
                ('featured', models.BooleanField(default=True, verbose_name='دورة مميزة (تظهر في الرئيسية)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب الظهور')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'دورة تدريبية',
                'verbose_name_plural': 'الدورات والبرامج التدريبية',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
