# Generated by Django 6.0.6 on 2026-09-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='export_batch',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='اسم/رمز دفعة التصدير'),
        ),
        migrations.AddField(
            model_name='registration',
            name='exported_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التصدير لملف Excel'),
        ),
        migrations.AddField(
            model_name='registration',
            name='is_exported',
            field=models.BooleanField(default=False, help_text='عند التصدير، يتم استبعاد الطالب من عداد المقاعد النشط بالواجهة لتبدأ دفعة جديدة من صفر', verbose_name='تم التصدير إلى Excel (أرشفة الدفعة)'),
        ),
    ]
